### ISSUE TITLE
Issues running faucet_util.py

### ISSUE THREAD

**Issue by tcrhyne** [karlfloersch/docker-pyeth-dev#14]
I've been able to get a miner up and running, but haven't been able to get the faucet_util.py to work as described. I'm wondering if my node needs to be fully caught up for the faucet to work, or if my understanding of the terminal command to initiate that transaction is incorrect.

I'm using the command suggested (`$$ python faucet_util.py $FAUCET_PRIV_KEY $YOUR_ADDRESS localhost`), but it doesn't look like the terminal variables in that command are actually defined anywhere, so I'm making the following substitutions:
- `$FAUCET_PRIV_KEY` = the key shown in config.yaml after running `make new-account`
- `$YOUR_ADDRESS` = the string shown in config/keystore

Thanks in advance, any help that you can provide is much appreciated.

**Comment by ChihChengLiang** [comment]
hi `$FAUCET_PRIV_KEY` is kept private for the testnet 1307. If you are running your own testnet, you can replace an address you own in `config.yaml`, and use the private key to that address in `faucet_util.py`.

**Comment by d00m178** [comment]
so where to get this `$FAUCET_PRIV_KEY` in my own testnet?
