### ISSUE TITLE
Multiple transactions in txqueue. Private network.

### ISSUE THREAD

**Issue by zarial6** [karlfloersch/docker-pyeth-dev#20]
Hello, after installing everything by example https://github.com/karlfloersch/docker-pyeth-dev/blob/master/readme.md#setup-local-testnet (POW+POS), we have encountered an issue where transaction processing has stopped and txqueue has kept growing up.

Every piece of logs in this document is from the Bootstrap node.

Here are the steps we've performed:

1) Created initial pow+pos network with bootstrap node and 1 miner.
2) Created new account for validator node.
3) Manually sent 5k ether to the new validator's node account via Web3j's new Transfer(...).sendFunds(...).
4) After ether has been succesfully added, we've performed activation of the validator node.
5) Then we created our internal Account entity and generated (via Web3j) a new wallet address for it.
6) Every new account receives 2 ether on creation from pre-allocated account on the bootstrap node (This operation was successful).
7) After we've sent 10 ether to this account from pre-allocated account on the bootstrap node (This also was fine and the account's balance became 17ether).
8) Then we've tried to deploy Zeppelin's MintableToken contract to our network which resulted to:

```
INFO:eth.chainservice   is mining? mining=False
INFO:eth.chain  Adding to head head=f6519b81590d45e8a3633efd219f3a9e9bcfd0d9b0594cabfc110c4d26a7ec9c
INFO:eth.chain  Reorganizing chain to block 37 (8e78e096) with 3 txs and 79210 gas
INFO:eth.validator      CASPER STATUS: epoch 0, 0.000 / 0.000 ETH (0.00 %) voted from current dynasty, 0.000 / 0.000 ETH (0.00 %) voted from previous dynasty, last finalized epoch 0 justified 0 expected source 0. Nonvoter deposits last rescaled 0.00000x, voter deposits 0.00000x
INFO:eth.chain  Changed head to: 37
INFO:eth.chainservice   added block=<ethereum.block.Block object at 0x7fc941018ba8> txs=3 gas_used=79210
INFO:eth.chainservice   processing time last=0.4131917953491211 avg=0.20871604919433595 max=0.4131917953491211 min=0.15994644165039062 median=0.19772577285766602
```

9) From here we decided to test if 10 subsequent sendFunds(...) transactions with 1 ether each are going to work. 
   We manually sent 10 requests to our backend within 20 seconds which resulted in an increasing txqueue and only 1 transaction gotten added to the block. 
   Account's balance has became 18 ether instead of 27.

The log is: 

```
INFO:eth.chainservice   is mining? mining=False
INFO:eth.block  Adding transactions, 1 in txqueue, 0 dunkles
INFO:eth.block  Added 1 transactions
INFO:eth.block  Block pre-sealed, 21000 gas used
INFO:eth.chainservice   is mining? mining=False
INFO:eth.block  Adding transactions, 2 in txqueue, 0 dunkles
INFO:eth.block  Added 2 transactions
INFO:eth.block  Block pre-sealed, 42000 gas used
INFO:eth.chainservice   is mining? mining=False
INFO:eth.block  Adding transactions, 3 in txqueue, 0 dunkles
INFO:eth.block  Added 3 transactions
INFO:eth.block  Block pre-sealed, 63000 gas used
INFO:eth.chainservice   is mining? mining=False
INFO:eth.block  Adding transactions, 4 in txqueue, 0 dunkles
INFO:eth.block  Added 4 transactions
INFO:eth.block  Block pre-sealed, 84000 gas used
INFO:eth.chainservice   is mining? mining=False
INFO:eth.block  Adding transactions, 5 in txqueue, 0 dunkles
INFO:eth.block  Added 5 transactions
INFO:eth.block  Block pre-sealed, 105000 gas used
INFO:eth.chainservice   is mining? mining=False
INFO:eth.block  Adding transactions, 6 in txqueue, 0 dunkles
INFO:eth.block  Added 6 transactions
INFO:eth.block  Block pre-sealed, 126000 gas used
INFO:eth.chainservice   is mining? mining=False
INFO:eth.block  Adding transactions, 7 in txqueue, 0 dunkles
INFO:eth.block  Added 7 transactions
INFO:eth.block  Block pre-sealed, 147000 gas used
INFO:eth.chainservice   is mining? mining=False
INFO:eth.block  Adding transactions, 8 in txqueue, 0 dunkles
INFO:eth.block  Added 8 transactions
INFO:eth.block  Block pre-sealed, 168000 gas used
INFO:eth.chainservice   is mining? mining=False
INFO:eth.block  Adding transactions, 9 in txqueue, 0 dunkles
INFO:eth.block  Added 9 transactions
INFO:eth.block  Block pre-sealed, 189000 gas used
INFO:eth.chainservice   is mining? mining=False
 
INFO:eth.chain  Adding to head head=8e78e09607afab5422bfedf994b5029a1a8352a48f1e93e742219520f52bba7b
INFO:eth.chain  Reorganizing chain to block 38 (0ceef808) with 1 txs and 21000 gas
INFO:eth.validator      CASPER STATUS: epoch 0, 0.000 / 0.000 ETH (0.00 %) voted from current dynasty, 0.000 / 0.000 ETH (0.00 %) voted from previous dynasty, last finalized epoch 0 justified 0 expected source 0. Nonvoter deposits last rescaled 0.00000x, voter deposits 0.00000x
INFO:eth.chain  Changed head to: 38
INFO:eth.chainservice   added block=<ethereum.block.Block object at 0x7fc94115a9e8> txs=1 gas_used=21000
INFO:eth.chainservice   processing time last=0.2890758514404297 avg=0.2118068108191857 max=0.4131917953491211 min=0.15994644165039062 median=0.19811129570007324
INFO:eth.block  Adding transactions, 9 in txqueue, 0 dunkles
INFO:eth.block  Added 9 transactions
INFO:eth.block  Block pre-sealed, 189000 gas used
```
10) After these steps any subsequent transaction is added to the txqueue and none transaction completes normally. The messages we receive are like this: 

```
INFO:eth.chain  Adding to head head=388bcf64b9ad17560d33e6d866912c24b1d33a8d4d34bd5f56698f5839987cee
INFO:eth.chain  Reorganizing chain to block 42 (4b010621) with 0 txs and 0 gas
INFO:eth.validator      CASPER STATUS: epoch 0, 0.000 / 0.000 ETH (0.00 %) voted from current dynasty, 0.000 / 0.000 ETH (0.00 %) voted from previous dynasty, last finalized epoch 0 justified 0 expected source 0. Nonvoter deposits last rescaled 0.00000x, voter deposits 0.00000x
INFO:eth.chain  Changed head to: 42
INFO:eth.chainservice   added block=<ethereum.block.Block object at 0x7fc941178e48> txs=0 gas_used=0
INFO:eth.chainservice   processing time last=0.2781689167022705 avg=0.22850781281789143 max=0.4535088539123535 min=0.15994644165039062 median=0.2093188762664795
INFO:eth.block  Adding transactions, 15 in txqueue, 0 dunkles
ERROR:eth.block <Transaction(f5c3)>: 'nonce' actual:18 target:9
ERROR:eth.block <Transaction(3747)>: 'nonce' actual:18 target:9
ERROR:eth.block <Transaction(1c53)>: 'nonce' actual:18 target:9
ERROR:eth.block <Transaction(6422)>: 'nonce' actual:18 target:10
ERROR:eth.block <Transaction(d086)>: 'nonce' actual:18 target:10
ERROR:eth.block <Transaction(3043)>: 'nonce' actual:18 target:10
INFO:eth.block  Added 9 transactions
INFO:eth.block  Block pre-sealed, 189000 gas used
```
We've experienced the same behavior when we were trying to send wei via curl in plain json-rpc command from the bootstrap node. 

The same as before only the first transaction has been added to the block and the balance of the account has been increased on the value from this first transaction. The rest transactions left in the txqueue and any subsequent transaction is followed by:

```
INFO:eth.block  Adding transactions, 6 in txqueue, 0 dunkles
ERROR:eth.block <Transaction(587f)>: 'nonce' actual:10 target:6
ERROR:eth.block <Transaction(938a)>: 'nonce' actual:10 target:6
INFO:eth.block  Added 4 transactions
INFO:eth.block  Block pre-sealed, 84000 gas used
```
We've even tried to send new transactions with the particular nonce (in the latter case: 6, 10 and 11), but no transactions have been added to the txqueue.

**Another** important issue is that any transaction, except balance check, completes exceptionally (after sendAsync via Web3j), but ether is still transferred. The exception is:
`org.web3j.protocol.exceptions.TransactionException: Error processing request: 'NoneType' object is not iterable; `

Thus, we're unable to read contract address after deployment or identify whether the sendFunds() transaction has completed normally (unless we check balance manually).

Web3J version is: web3j-spring-boot-starter 1.6.0
Pyethapp: pyethapp/1.5.0/linux/py3.6.3
OS: centos 7.4

**Comment by ChihChengLiang** [comment]
Not quite certain, but from current information might be your Web3j not getting the latest nonce of the account. So it sent a tx with the old nonce and thus fail.

**Comment by zarial6** [comment]
@ChihChengLiang, the same behavior occurs even without Web3j, but with plain json-rpc call like "eth_sendTransaction" or etc. Indeed, it seems like the nonce is not incremented or so, but from what we've experienced from poa on parity there should be at least a message saying that there might be another tx with the same nonce ("try to increase gas or increment nonce"). Event though, this behavior occurs during pretty aggressive network usage. Our case, instead, was simply sending 5-10 transactions manually (by sending eth_sendTransaction with params via console) in a row during 20-30 seconds.

Our main concern is the following: on simple private poa testnet, even if new transactions have the same nonce, nothing stops us from sending these transactions later and everything works fine; pow+pos implementation hangs instead with increasing txqueue.

**Comment by ChihChengLiang** [comment]
As mentioned in [gitter channel](https://gitter.im/ethereum/casper?at=5ae0695b270d7d370804722f), [Harmony](https://github.com/mkalinin/harmony-docker/tree/master/casper) is now a better option for users to test Casper for the time being.
